"""
Detailed AcroForm field read/write for the in-app field editor (Phase 6).

`core.pdf_extraction` already reads field values for the data table, but it
deliberately flattens everything to plain strings (it doesn't need to know a
field is a checkbox vs. free text -- a table cell is a table cell). The
field editor needs more: it has to render a checkbox as a checkbox, a
dropdown as a dropdown, and know a checkbox's actual "on" state name (which
is not always "/Yes", even though that's what our own LaTeX template uses)
so it can write a value pypdf/Acrobat will actually recognize.

No Qt dependency on purpose -- unit-tested headlessly against a real
generated PDF (see project dev notes), same convention as pdf_extraction.py.
"""

from __future__ import annotations

import os
import tempfile
import uuid
from dataclasses import dataclass, field as dataclass_field
from pathlib import Path
from typing import Literal

from pypdf import PdfReader, PdfWriter
from pypdf.errors import PdfReadError
from pypdf.generic import ArrayObject, FloatObject, NameObject, NumberObject, StreamObject

FieldType = Literal["text", "checkbox", "choice", "other"]


@dataclass
class FieldInfo:
    name: str
    field_type: FieldType
    value: str  # normalized: "" / "Yes" for checkboxes, plain text/choice otherwise
    on_state: str = "Yes"  # checkbox only -- the real PDF name meaning "checked"
    choices: list[str] = dataclass_field(default_factory=list)  # choice fields only


def read_fields_detailed(pdf_path: Path) -> list[FieldInfo]:
    """Read every AcroForm field of `pdf_path` with enough type information
    to build an editing widget for it. Field order matches the PDF's own
    field dictionary order (insertion order), same as get_fields()."""
    reader = PdfReader(str(pdf_path))
    fields = reader.get_fields() or {}

    result: list[FieldInfo] = []
    for name, field_obj in fields.items():
        field_type = field_obj.get("/FT")
        raw_value = field_obj.get("/V")

        if field_type == "/Btn":
            states = field_obj.get("/_States_") or []
            on_state = "Yes"
            for state in states:
                state_name = str(state).lstrip("/")
                if state_name != "Off":
                    on_state = state_name
                    break
            checked = isinstance(raw_value, str) and raw_value.lstrip("/") == on_state
            result.append(
                FieldInfo(
                    name=str(name),
                    field_type="checkbox",
                    value="Yes" if checked else "",
                    on_state=on_state,
                )
            )
        elif field_type == "/Ch":
            choices: list[str] = []
            for opt in field_obj.get("/Opt") or []:
                choices.append(str(opt[-1]) if isinstance(opt, (list, tuple)) else str(opt))
            value = "" if raw_value is None else str(raw_value)
            result.append(
                FieldInfo(name=str(name), field_type="choice", value=value, choices=choices)
            )
        elif field_type == "/Tx":
            value = "" if raw_value is None else str(raw_value)
            result.append(FieldInfo(name=str(name), field_type="text", value=value))
        else:
            # Signature fields and anything else we don't have a sensible
            # editor for -- surfaced as read-only "other" so the dialog can
            # show it without offering to edit it.
            value = "" if raw_value is None else str(raw_value)
            result.append(FieldInfo(name=str(name), field_type="other", value=value))

    return result


def repair_checkbox_appearances(writer: PdfWriter) -> int:
    """Fixes a real, independently-documented bug in hyperref itself
    (https://github.com/latex3/hyperref/issues/94, open since 2019): the
    "checked" appearance of a \\CheckBox is written into the PDF as a
    syntactically empty dictionary instead of a real content stream. Per
    the PDF spec every checkbox state needs its own appearance stream to
    be drawn at all -- with an empty one, *no* renderer can show a
    checked box correctly, this app's own preview included, regardless
    of any other fix (NeedAppearances, flattening, ...). This affects
    every PDF generated by LaTeX_Template, filled by any tool whatsoever,
    not just PDFs touched by this app's own editor.

    Replaces any such empty on-state appearance with a real, minimal
    checkmark drawing sized to the widget's own rectangle, in the
    template's own accent green. Safe to call on an already-repaired (or
    never-broken) PDF -- only touches appearances that are actually
    empty. Returns how many appearances were repaired, purely for
    logging/debugging.
    """
    repaired = 0
    for page in writer.pages:
        for annot in page.get("/Annots") or []:
            obj = annot.get_object()
            if obj.get("/FT") != "/Btn":
                continue
            ap = obj.get("/AP")
            if not ap or "/N" not in ap:
                continue
            n_obj = ap["/N"]
            if not hasattr(n_obj, "items"):
                continue  # already a single, direct stream -- nothing to repair
            rect = obj.get("/Rect")
            if rect is None:
                continue
            width = float(rect[2]) - float(rect[0])
            height = float(rect[3]) - float(rect[1])
            for state_name in list(n_obj.keys()):
                if state_name == "/Off":
                    continue  # a blank appearance is *correct* when unchecked
                appearance = n_obj[state_name]
                is_empty = not hasattr(appearance, "get_data") or len(appearance.get_data()) == 0
                if not is_empty:
                    continue
                stream = _build_checkmark_stream(width, height)
                n_obj[NameObject(state_name)] = writer._add_object(stream)
                repaired += 1
    return repaired


def _build_checkmark_stream(width: float, height: float) -> StreamObject:
    """A minimal PDF Form XObject that draws a simple checkmark filling
    most of a `width` x `height` box, in the template's own accent green
    (RGB 74/124/60, see LaTeX_Template/event-form-style.sty)."""
    margin = min(width, height) * 0.2
    x0, y0 = margin, height * 0.45
    x1, y1 = width * 0.42, margin
    x2, y2 = width - margin, height - margin
    line_width = max(1.0, min(width, height) * 0.12)

    content = (
        f"{line_width:.2f} w 1 J 1 j\n"
        f"0.29 0.49 0.24 RG\n"
        f"{x0:.2f} {y0:.2f} m\n"
        f"{x1:.2f} {y1:.2f} l\n"
        f"{x2:.2f} {y2:.2f} l\n"
        f"S\n"
    ).encode("latin-1")

    stream = StreamObject()
    stream.set_data(content)
    stream[NameObject("/Type")] = NameObject("/XObject")
    stream[NameObject("/Subtype")] = NameObject("/Form")
    stream[NameObject("/FormType")] = NumberObject(1)
    stream[NameObject("/BBox")] = ArrayObject(
        [FloatObject(0), FloatObject(0), FloatObject(width), FloatObject(height)]
    )
    return stream


def build_flattened_preview_copy(pdf_path: Path) -> Path:
    """Builds a temporary, throwaway copy of `pdf_path` for PDF-preview
    rendering ONLY, with every field's current value baked directly into
    the page content ("flattened") and checkbox appearances repaired
    (see repair_checkbox_appearances). The original file on disk is
    never touched, and its AcroForm fields stay fully live/editable --
    only the temp copy is flattened.

    This exists because this app's own PDF preview
    (QPdfDocument.render(), see panels/preview_panel.py) does not
    reliably draw AcroForm field/widget annotations even with the
    Annotations render flag set on -- a real, confirmed limitation of
    Qt's PDF module, not something fixable by more render-option
    tweaking. Flattening sidesteps the problem entirely: a flattened
    field's value becomes completely ordinary page content, which every
    PDF renderer already draws correctly, annotation support or not.

    Caller owns the returned path and is responsible for deleting it
    once done (e.g. when replacing it with a fresh preview).
    """
    reader = PdfReader(str(pdf_path))
    writer = PdfWriter()
    writer.append(reader)

    repair_checkbox_appearances(writer)

    # Re-apply every field's own current value through flatten=True --
    # this changes no data, it only bakes what's already there into the
    # page's content stream.
    values: dict[str, str] = {}
    for name, field_obj in (reader.get_fields() or {}).items():
        value = field_obj.get("/V")
        if value is not None:
            values[str(name)] = str(value)
    if values:
        writer.update_page_form_field_values(None, values, auto_regenerate=False, flatten=True)

    tmp_path = Path(tempfile.gettempdir()) / f"registration_manager_preview_{uuid.uuid4().hex}.pdf"
    with open(tmp_path, "wb") as handle:
        writer.write(handle)
    return tmp_path


def write_fields(pdf_path: Path, fields: list[FieldInfo]) -> None:
    """Write `fields` (as returned by read_fields_detailed, with `.value`
    updated by the caller) back into `pdf_path`.

    Writes to a temporary file in the same directory first and only
    replaces the original via os.replace() once the write fully succeeds,
    so a crash or a locked file never leaves a half-written/corrupt PDF
    behind.
    """
    reader = PdfReader(str(pdf_path))
    writer = PdfWriter()
    writer.append(reader)

    # Harmless no-op on an already-repaired PDF; self-heals hyperref's
    # broken checkbox appearances (see repair_checkbox_appearances) the
    # first time this app's editor touches an old/external file that
    # still has them, on top of whatever LaTeX_Template's own build step
    # already fixed for freshly-generated ones.
    repair_checkbox_appearances(writer)

    pdf_values: dict[str, str] = {}
    for info in fields:
        if info.field_type == "checkbox":
            pdf_values[info.name] = f"/{info.on_state}" if info.value == "Yes" else "/Off"
        elif info.field_type in ("text", "choice"):
            pdf_values[info.name] = info.value
        # "other" (e.g. signature) fields are never written back.

    # auto_regenerate=False is deliberate and load-bearing, not just a
    # style choice: it tells pypdf to bake a real, immediately-visible
    # appearance stream into each field's /AP right now, and to clear the
    # PDF's /NeedAppearances flag (which the original LaTeX_Template
    # already ships as true, since hyperref sets it by default). If that
    # flag is left/set true instead, the file's *data* is still correct --
    # the app's own table reads /V directly and was never affected -- but
    # any viewer that takes the flag at face value and doesn't actually
    # regenerate appearances itself (this app's own PDF preview included,
    # since it's a lightweight embedded renderer, not a full interactive
    # form engine -- and pypdf's own docs note several common viewers
    # behave this way) renders the field as blank, even though the value
    # is genuinely saved. This was a real bug: an earlier version of this
    # function forced auto_regenerate=False and then immediately re-set
    # the flag anyway via set_need_appearances_writer(True) right after,
    # which undid the whole point and left every field invisible in this
    # app's own preview pane despite being saved correctly.
    writer.update_page_form_field_values(None, pdf_values, auto_regenerate=False)

    tmp_path = pdf_path.with_name(pdf_path.name + ".tmp")
    try:
        with open(tmp_path, "wb") as handle:
            writer.write(handle)
        os.replace(tmp_path, pdf_path)
    finally:
        if tmp_path.exists():
            tmp_path.unlink(missing_ok=True)


class FieldWriteError(Exception):
    """Raised by write_fields callers on any I/O or PDF-parsing failure --
    a thin, dialog-friendly wrapper so the GUI layer doesn't need to know
    about pypdf's own exception types."""


def safe_write_fields(pdf_path: Path, fields: list[FieldInfo]) -> None:
    try:
        write_fields(pdf_path, fields)
    except (PdfReadError, OSError, ValueError) as exc:
        raise FieldWriteError(str(exc)) from exc
